export const iconMapping = {
  '.json': 'json-lang-file-icon',
  '.prettierrc': 'json-lang-file-icon',
  '.js': 'javascript-lang-file-icon',
  '.jsx': 'javascript-lang-file-icon',
  '.ts': 'typescriptreact-lang-file-icon',
  '.tsx': 'typescriptreact-lang-file-icon',
  '.html': 'html-lang-file-icon',
  '.css': 'css-lang-file-icon',
  '.less': 'less-lang-file-icon',
  '.py': 'python-lang-file-icon',
  '.md': 'markdown-lang-file-icon',
  '.eslintignore': 'ignore-lang-file-icon',
  '.npmignore': 'ignore-lang-file-icon',
  '.gitignore': 'ignore-lang-file-icon',
  '.prettierignore': 'ignore-lang-file-icon',
  '.preview': 'javascriptreact-lang-file-icon',
  '.editorconfig': 'properties-lang-file-icon',
};
